name: Update change log
on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_update]
  schedule:
    - cron: '50 5 * * 0,3'

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get install subversion -y
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --without dev
      - name: Update file
        run: |
          bash update_file.sh
          cd gene_characterisation_status
          bash get_latest_numbers.sh
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updated to last revision
          file_pattern: "*.tsv gene_characterisation_status/latest_revision/*.txt gene_characterisation_status/latest_revision/*.tsv"
